Project/EducationalProgramGenerator.WEB/Controllers/AcademicPlanController.cs
using EducationalProgramGenerator.BLL.DTO;
using EducationalProgramGenerator.BLL.Interfaces;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using System.Xml.Linq;

namespace EducationalProgramGenerator.WEB.Controllers
{
    [Authorize(Roles = "superuser, admin")]
    public class AcademicPlanController : BaseController
    {
        private IAcademicPlanService AcademicPlanService
        {
            get
            {
                return HttpContext.GetOwinContext().Get<IAcademicPlanService>();
            }
        }

        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            base.OnActionExecuting(filterContext);
            var userFromAuthCookie = System.Threading.Thread.CurrentPrincipal;

            var user = UserService.FindByUserName(userFromAuthCookie.Identity.Name);
            if (user.StructureDepartmentId == 0)
            {
                filterContext.Result = new RedirectToRouteResult(new RouteValueDictionary(new
                {
                    controller = "Home",
                    action = "Message",
                    message = "Сначала установите структурное подразделение"
                }));
            }
        }

        public ActionResult Index()
        {
            var structureDepartmentId = UserService.FindByUserName(User.Identity.Name).StructureDepartmentId;
            ViewBag.Plans = AcademicPlanService.GetAcademicPlansNames(structureDepartmentId);
            return View();
        }

        [HttpPost]
        public ActionResult Upload(HttpPostedFileBase upload)
        {
            if (upload != null)
            {
                var user = UserService.FindByUserName(User.Identity.Name);
                XDocument document = XDocument.Load(upload.InputStream);
                AcademicPlanService.SaveAcademicPlan(document, user.StructureDepartmentId);
            }
            return RedirectToAction("Index");
        }

        public ActionResult GetAcademicPlans()
        {
            var structureDepartmentId = UserService.FindByUserName(User.Identity.Name).StructureDepartmentId;
            ViewBag.AcademicPlans = AcademicPlanService.GetAcademicPlans(structureDepartmentId);
            return View();
        }

        public ActionResult EditAcademicPlan(string plan)
        {
            var structureDepartmentId = UserService.FindByUserName(User.Identity.Name).StructureDepartmentId;
            ViewBag.AcademicPlan = AcademicPlanService.GetAcademicPlan(structureDepartmentId, plan);
            return View();
        }
    }
}

Project/EducationalProgramGenerator.WEB/Controllers/RpdGeneratorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using EducationalProgramGenerator.WEB.Models;
using EducationalProgramGenerator.BLL.Interfaces;
using Microsoft.AspNet.Identity.Owin;
using System.Web.Routing;
using EducationalProgramGenerator.BLL.DTO;
using Newtonsoft.Json;
using EducationalProgramGenerator.WEB.HtmlHelper;
using System.Web.Script.Serialization;
using System.Reflection;
using EducationalProgramGenerator.BLL.Services;
using System.ComponentModel.DataAnnotations;
using System.Dynamic;

namespace EducationalProgramGenerator.WEB.Controllers
{
    [Authorize]
    public class RpdGeneratorController : BaseController
    {
        private IAcademicPlanService AcademicPlanService
        {
            get
            {
                return HttpContext.GetOwinContext().Get<IAcademicPlanService>();
            }
        }

        private IDocumentGeneratorService DocumentGeneratorService
        {
            get
            {
                return HttpContext.GetOwinContext().Get<IDocumentGeneratorService>();
            }
        }

        private IDisciplineService DisciplineService
        {
            get
            {
                return HttpContext.GetOwinContext().Get<IDisciplineService>();
            }
        }

        private IRpdParserService RpdParserService
        {
            get
            {
                return HttpContext.GetOwinContext().Get<IRpdParserService>();
            }
        }

        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            base.OnActionExecuting(filterContext);
            var userFromAuthCookie = System.Threading.Thread.CurrentPrincipal;

            var user = UserService.FindByUserName(userFromAuthCookie.Identity.Name);
            if (user.StructureDepartmentId == 0)
            {
                filterContext.Result = new RedirectToRouteResult(new RouteValueDictionary(new
                {
                    controller = "Home",
                    action = "Message",
                    message = "Сначала установите структурное подразделение"
                }));
            }
        }

        public ActionResult Index()
        {
            var structureDepartmentId = UserService.FindByUserName(User.Identity.Name).StructureDepartmentId;
            ViewBag.Plans = AcademicPlanService.GetAcademicPlansNames(structureDepartmentId);
            return View();
        }

        public ActionResult DisciplineInformation(string discipline, string plan)
        {
            var structureDepartmentId = UserService.FindByUserName(User.Identity.Name).StructureDepartmentId;
            ViewBag.Plan = plan;
            ViewBag.Discipline = discipline;

            var authors = UserService.GetAll();
            ViewBag.Authors = authors;
            var currentAuthors = DisciplineService.GetAuthors(structureDepartmentId, plan, discipline);
            ViewBag.SelectedAuthors =
                authors.Select(item => currentAuthors.Exists(x => x.Id == item.Id)).ToList();

            ViewBag.Goals = DisciplineService.GetGoals(structureDepartmentId, discipline, plan);
            ViewBag.Tasks = DisciplineService.GetTasks(structureDepartmentId, discipline, plan);

            ViewBag.StartYear = AcademicPlanService.GetStartYear(structureDepartmentId, plan);

            var previousDisciplines = AcademicPlanService.GetPreviousDisciplinesNames(structureDepartmentId, plan, discipline);
            ViewBag.PreviousDisciplines = previousDisciplines;
            var currentPreviousDisciplines = DisciplineService.GetPreviousDisciplines(structureDepartmentId, discipline, plan);
            ViewBag.SelectedPreviousDisciplines =
                previousDisciplines.Select(item => currentPreviousDisciplines.Contains(item)).ToList();

            var nextDisciplines = AcademicPlanService.GetNextDisciplinesNames(structureDepartmentId, plan, discipline);
            ViewBag.NextDisciplines = nextDisciplines;
            var currentNextDisciplines = DisciplineService.GetNextDisciplines(structureDepartmentId, discipline, plan);
            ViewBag.SelectedNextDisciplines =
                nextDisciplines.Select(item => currentNextDisciplines.Contains(item)).ToList();

            return View();
        }

        [HttpPost]
        public ActionResult Index(string discipline, string plan)
        {
            var structureDepartmentId = UserService.FindByUserName(User.Identity.Name).StructureDepartmentId;
            ViewBag.Plan = plan;
            ViewBag.Discipline = discipline;

            ViewBag.StartYear = AcademicPlanService.GetStartYear(structureDepartmentId, plan);

            return View("Menu");   
        }

        public ActionResult Menu(string discipline, string plan)
        {
            var structureDepartmentId = UserService.FindByUserName(User.Identity.Name).StructureDepartmentId;
            ViewBag.Plan = plan;
            ViewBag.Discipline = discipline;

            ViewBag.StartYear = AcademicPlanService.GetStartYear(structureDepartmentId, plan);

            return View();
        }

        [HttpPost]
        public ActionResult EditDiscipline(EditDisciplineViewModel model, string plan, string discipline)
        {

            var dto = new DisciplineDTO(discipline, model.Goals+"\n"+model.Tasks);
            //dto.AuthorId = model.Author;

            var structureDepartmentId = UserService.FindByUserName(User.Identity.Name).StructureDepartmentId;
            var competencies = AcademicPlanService.GetDisciplineCompetencies(structureDepartmentId, plan, discipline);

            for (int i = 0; i < model.Competencies.Count; ++i)
            {
                var competency = new CompetencyDTO(competencies[i].Description, competencies[i].Code);
                competency.Children.Add(new LearningOutcomesDTO(model.Competencies[i].ToKnow));
                competency.Children.Add(new LearningOutcomesDTO(model.Competencies[i].ToCan));
                competency.Children.Add(new LearningOutcomesDTO(model.Competencies[i].ToOwn));
                dto.Results.Add(competency);
            }


            //ViewBag.Url = DocumentGeneratorService.CreateDocument(plan, discipline, dto);
            return View("DownloadDocument");
        }

        #region Информация о дисциплине
        public JsonResult AddGoals(string goals, string plan, string discipline)
        {
            var structureDepartmentId = UserService.FindByUserName(User.Identity.Name).StructureDepartmentId;
            DisciplineService.AddGoals(structureDepartmentId, plan, discipline, goals);
            return Json(new { data = "success" });
        }

        public JsonResult AddTasks(string tasks, string plan, string discipline)
        {
            var structureDepartmentId = UserService.FindByUserName(User.Identity.Name).StructureDepartmentId;
            DisciplineService.AddTasks(structureDepartmentId, plan, discipline, tasks);
            return Json(new { data = "success" });
        }

        public JsonResult AddPreviousDiscipline(string previous, string plan, string discipline)
        {
            var structureDepartmentId = UserService.FindByUserName(User.Identity.Name).StructureDepartmentId;
            DisciplineService.AddPreviousDiscipline(structureDepartmentId, plan, discipline, previous);
            return Json(new { data = "success" });
        }

        public JsonResult RemovePreviousDiscipline(string previous, string plan, string discipline)
        {
            var structureDepartmentId = UserService.FindByUserName(User.Identity.Name).StructureDepartmentId;
            DisciplineService.RemovePreviousDiscipline(structureDepartmentId, plan, discipline, previous);
            return Json(new { data = "success" });
        }

        public JsonResult AddNextDiscipline(string next, string plan, string discipline)
        {
            var structureDepartmentId = UserService.FindByUserName(User.Identity.Name).StructureDepartmentId;
            DisciplineService.AddNextDiscipline(structureDepartmentId, plan, discipline, next);
            return Json(new { data = "success" });
        }

        public JsonResult RemoveNextDiscipline(string next, string plan, string discipline)
        {
            var structureDepartmentId = UserService.FindByUserName(User.Identity.Name).StructureDepartmentId;
            DisciplineService.RemoveNextDiscipline(structureDepartmentId, plan, discipline, next);
            return Json(new { data = "success" });
        }

        public JsonResult AddDisciplineAuthor(string id, string plan, string discipline)
        {
            var structureDepartmentId = UserService.FindByUserName(User.Identity.Name).StructureDepartmentId;
            DisciplineService.AddAuthor(structureDepartmentId, plan, discipline, id);
            return Json(new { data = "success" });
        }

        public JsonResult RemoveDisciplineAuthor(string id, string plan, string discipline)
        {
            var structureDepartmentId = UserService.FindByUserName(User.Identity.Name).StructureDepartmentId;
            DisciplineService.RemoveAuthor(structureDepartmentId, plan, discipline, id);
            return Json(new { data = "success" });
        }
        #endregion

        #region Структура дисциплины
        public ActionResult EditStructure(string discipline, string plan)
        {
            var structureDepartmentId = UserService.FindByUserName(User.Identity.Name).StructureDepartmentId;
            ViewBag.Plan = plan;
            ViewBag.Discipline = discipline;
            ViewBag.StartYear = AcademicPlanService.GetStartYear(structureDepartmentId, plan);
            ViewBag.Semesters = AcademicPlanService.GetDiscipline(structureDepartmentId, plan, discipline)
                .Children.Select(x => x.OrderNumber);
            return View();
        }

Project/EducationalProgramGenerator.WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <!--Иконки Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/select2")
    @RenderSection("scripts", required: false)
    @Scripts.Render("~/bundles/app")
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
                $.widget.bridge('uibutton', $.ui.button);
    </script>
</head>
<body class="hold-transition skin-black-light sidebar-mini">
    
    <div class="wrapper">
        <!-- Main Header -->
        <header class="main-header">
            <!-- Лого -->
            <a href="/" class="logo">
                <!-- мини лого для сайдбара 50x50  -->
                <span class="logo-mini"><b>O</b>EDU</span>
                <!-- Нормальное лого -->
                <span class="logo-lg"><b>Open</b>Education</span>
            </a>
            <!-- Header Navbar -->
            <nav class="navbar navbar-static-top" role="navigation">
                <!-- Navbar Right Menu -->
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <!-- User Account Menu -->
                        <li class="dropdown user user-menu">
                            <!-- Menu Toggle Button -->
                            @Html.Partial("_LoginPartial")
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <aside class="main-sidebar">
            <section class="sidebar">

                <!-- Sidebar Menu -->
                <ul class="sidebar-menu">
                    <li class="header">Меню</li>
                    <!-- Optionally, you can add icons to the links -->
                    @if (User.IsInRole("superuser"))
                    {
                        <li class="treeview">
                            <a href="#">
                                <i class="fa fa-magic"></i> <span>Учебные планы</span>
                                <span class="pull-right-container">
                                    <i class="fa fa-angle-left pull-right"></i>
                                </span>
                            </a>
                            <ul class="treeview-menu">
                                <li><a href="@Html.Raw(Url.Action("GetAcademicPlans", "AcademicPlan"))"><i class="fa fa-circle-o"></i> Список УП</a></li>
                                <li><a href="@Html.Raw(Url.Action("Index", "AcademicPlan"))"><i class="fa fa-circle-o"></i> Загрузить УП</a></li>
                            </ul>
                        </li>
                    }
                    <li class="treeview">
                        <a href="#">
                            <i class="fa fa-magic"></i> <span>Генератор РПД</span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li>
                                @Html.ActionLink("Мои РПД", "GetUserRPDs", "RpdGenerator")
                            </li>
                            @if (User.IsInRole("superuser"))
                            {
                                <li>
                                    @Html.ActionLink("Выбор дисциплины", "Index", "RpdGenerator")
                                </li>
                            }
                            @if (ViewBag.Plan != null) {
                                @:<li><a href = "@Html.Raw(Url.Action("DisciplineInformation", "RpdGenerator", new { @plan = ViewBag.Plan, @discipline = ViewBag.Discipline }))" ><i class="fa fa-circle-o"></i> Информация о курсе</a></li>
                                @:<li><a href = "@Html.Raw(Url.Action("EditLiterature", "RpdGenerator", new { @plan = ViewBag.Plan, @discipline = ViewBag.Discipline }))" ><i class="fa fa-circle-o"></i> Литература</a></li>
                                @:<li><a href = "@Html.Raw(Url.Action("EditCompetencies", "RpdGenerator", new { @plan = ViewBag.Plan, @discipline = ViewBag.Discipline }))" ><i class="fa fa-circle-o"></i> Компетенции</a></li>
                                @:<li><a href = "@Html.Raw(Url.Action("EditStructure", "RpdGenerator", new { @plan = ViewBag.Plan, @discipline = ViewBag.Discipline }))" ><i class="fa fa-circle-o"></i> Структура курса</a></li>
                                @:<li><a href="@Html.Raw(Url.Action("CopyRPD", "RpdGenerator", new { @plan = ViewBag.Plan, @discipline = ViewBag.Discipline }))"><i class="fa fa-circle-o"></i> Копирование дисциплины</a></li>
                                @:<li><a href="@Html.Raw(Url.Action("GenerateRPD", "RpdGenerator", new { @plan = ViewBag.Plan, @discipline = ViewBag.Discipline }))"><i class="fa fa-circle-o"></i> Скачать документ</a></li>
                            }
                        </ul>
                    </li>
                </ul>
                <!-- /.sidebar-menu -->
            </section>
            <!-- /.sidebar -->
        </aside>
    <div class="content-wrapper" style="min-height: 500px;">
        @RenderBody()
    </div>

    </div>
  
        <!-- Left side column. contains the logo and sidebar -->

    <footer class="main-footer">
        <!-- To the right -->
        <div class="pull-right hidden-xs">
            Челябинский Государственный Университет
        </div>
        <!-- Default to the left -->
        <strong>Copyright &copy; @DateTime.Now.Year <a href="/">Институт Информационных Технологий</a>.</strong>
    </footer>
</body>
</html >